const SpeakersData = [
  // Conference Chair
  {
    name: "Dr. Marilyn Morales Obod",
    title: "Research Director,",
    title2: "Former Dean of the MAED Program of the Graduate School,",
    title3: "World Citi Colleges,",
    title4: "Philippines.",
    image: "/images/speakers/marilyn.webp",
    role: "Conference Chair",
    country: "Philippines",
  },

  // Keynote Speakers
  {
    name: "Dr. Renante Apelado Diamante",
    title: "Associate Professor,",
    title2: "College of Information and Communications Technology,",
    title3: "ISUFST,",
    title4: "Philippines.",
    image: "/images/speakers/renante.png",
    role: "Keynote Speakers",
    country: "Philippines",
  },
  {
    name: "Dr. Nelson B. Guillen Jr.",
    title: "Assistant Dean for External Affairs and Lasallian Mission,",
    title2: "Ramon V. del Rosario College of Business,",
    title3: "De La Salle University,",
    title4: "Manila, Philippines.",
    image: "/images/speakers/nelson.webp",
    role: "Keynote Speakers",
    country: "Philippines",
  },
  {
    name: "Prof. Dr. Kashif Hasan Khan",
    title: "Professor of Economics and Finance,",
    title2: "Dean, School of Graduate Studies,",
    title3: "Head, Department of Economics,",
    title4: "Paragon International University,",
    title5: "Phnom Penh, Cambodia.",
    image: "/images/speakers/kashif.jpeg",
    role: "Keynote Speakers",
    country: "Cambodia",
  },
  {
    name: "Prof. Dr. Khalid Hussain",
    title: "Professor (Cybersecurity),",
    title2: "School of Computing and Informatics,",
    title3: "Albukhary International University,",
    title4: "Malaysia.",
    image: "/images/speakers/khalid.jpeg",
    role: "Keynote Speakers",
    country: "Malaysia",
  },
  {
    name: "Dr. Eriki Ananda Kumar",
    title: "Principal and Professor of Mechanical Engineering,",
    title2: "SV College of Engineering,",
    title3: "Andhra Pradesh,",
    title4: "India.",
    image: "/images/speakers/eriki.png",
    role: "Keynote Speakers",
    country: "India",
  },

  // Session Chairs
  {
    name: "Dr. Joy Casi Lawenko",
    title: "Chairperson,",
    title2: "Department of Business Administration,",
    title3: "Bicol University College of Business, Economics and Management (BUCBEM),",
    title4: "Philippines.",
    image: "/images/speakers/joy.png",
    role: "Session Chairs",
    country: "Philippines",
  },
  {
    name: "Prof. Dr. Mostafa Ewees",
    title: "Stanford Educational Psychology & Psychoanalysis Professor,",
    title2: "Stanford University,",
    title3: "California,",
    title4: "Pathfinder Training Chairman.",
    image: "/images/speakers/mostafa.webp",
    role: "Session Chairs",
    country: "USA",
  },
  {
    name: "Dr. Shiva Shankar Reddy",
    title: "Associate Professor,",
    title2: "Department of Computer Science and Engineering,",
    title3: "Sagi Rama Krishnam Raju Engineering College,",
    title4: "India.",
    image: "/images/speakers/shiv.jpeg",
    role: "Session Chairs",
    country: "India",
  },

  // Session Speakers
  {
    name: "Mr. Patrick Hariramani",
    title: "Assistant Professor,",
    title2: "Director of the Department of Decision Sciences and Innovation,",
    title3: "De La Salle University,",
    title4: "Manila, Philippines.",
    image: "/images/speakers/patrick.webp",
    role: "Session Speakers",
    country: "Philippines",
  },
  {
    name: "Dr. P. Sri Ram Chandra",
    title: "Associate Professor,",
    title2: "Department of Computer Science and Engineering,",
    title3: "Aditya University,",
    title4: "Andhra Pradesh, India.",
    image: "/images/speakers/sri.png",
    role: "Session Speakers",
    country: "India",
  },
  {
    name: "Assoc. Prof. Dr. Mohd Zaki Bin Awang Chek",
    title: "Associate Professor,",
    title2: "Center for Actuarial Studies,",
    title3: "Faculty of Computer and Mathematical Sciences,",
    title4: "Universiti Teknologi MARA (UiTM),",
    title5: "Malaysia.",
    image: "/images/speakers/zaki.webp",
    role: "Session Speakers",
    country: "Malaysia",
  },
];

export default SpeakersData;